# MakeFile for CardiacFEM
# Defining variables
objects = precision.o global_variables.o mp_interface.o input.o output.o gather_scatter.o maths.o timing.o large_strain.o cardiacfem.o
f90comp = mpif90
flag = -O3
#Executable
CardiacFEM: $(objects)
    $(f90comp) -o CardiacFEM $(flag) $(objects)
# Objects
precision.o: precision.f90
    $(f90comp) -c $(flag) precision.f90
global_variables.o: global_variables.f90
    $(f90comp) -c $(flag) global_variables.f90
mp_interface.o: precision.o global_variables.o mp_interface.f90
    $(f90comp) -c $(flag) mp_interface.f90
input.o: precision.o mp_interface.o input.f90
    $(f90comp) -c $(flag) input.f90
output.o: precision.o mp_interface.o output.f90
    $(f90comp) -c $(flag) output.f90
loading.o: precision.o gather_scatter.o loading.f90
    $(f90comp) -c $(flag) loading.f90
maths.o: precision.o mp_interface.o maths.f90
    $(f90comp) -c $(flag) maths.f90
gather_scatter.o: precision.o mp_interface.o global_variables.o input.o gather_scatter.f90
    $(f90comp) -c $(flag) gather_scatter.f90
new_library.o: precision.o new_library.f90
    $(f90comp) -c $(flag) new_library.f90
large_strain.o: precision.o mp_interface.o gather_scatter.o loading.o maths.o new_library.o
    $(f90comp) -c $(flag) large_strain.f90
timing.o: precision.o timing.f90
    $(f90comp) -c $(flag) precision.f90
cardiacfem.o: precision.o global_variables.o mp_interface.o input.o output.o gather_scatter.o maths.o timing.o large_strain.o cardiacfem.f90
    $(f90comp) -c $(flag) cardiacfem.f90    
    

