# MakeFile for CardiacFEM



precision.o: precision.f90
    mpif90 -c precision.f90
    
global_variables: global_variables.f90
    mpif90 -c global_variables.f90
    
mp_interface.o: precision.o global_variables.o mp_interface.f90
    mpif90 -c mp_interface.f90
